### ISSUE TITLE
tdm.body.segment.data not loaded in kvn format

### ISSUE THREAD

**Issue by chessasds** [egemenimre/ccsds-ndm#15]
Hi,

I downloaded your project at the latest version 2.1 and I read a kvn file using the command

cdm = NdmIo().from_path(input_kvn_file)

and printing cmd I got

Tdm(header=TdmHeader(comment=[], creation_date='2016-09-30T12:48:03', originator='ESA', message_id=None), body=TdmBody(segment=[TdmSegment(metadata=TdmMetadata(comment=[], track_id=None, data_types=None, time_system=<TimeSystemType.UTC: 'UTC'>, start_time='2016-09-23T22:16:15.00', stop_time='2016-09-23T22:17:55.00', participant_1='ZIMLAT', participant_2='auto01', participant_3=None, participant_4=None, participant_5=None, mode=<ModeType.SEQUENTIAL: 'SEQUENTIAL'>, path='2,1', path_1=None, path_2=None, ephemeris_name_1=None, ephemeris_name_2=None, ephemeris_name_3=None, ephemeris_name_4=None, ephemeris_name_5=None, transmit_band=None, receive_band=None, turnaround_numerator=None, turnaround_denominator=None, timetag_ref=None, integration_interval=None, integration_ref=None, freq_offset=None, range_mode=None, range_modulus=None, range_units=None, angle_type=<AngleTypeType.RADEC: 'RADEC'>, reference_frame=<RefFrameType.EME2000: 'EME2000'>, interpolation=None, interpolation_degree=None, doppler_count_bias=None, doppler_count_scale=None, doppler_count_rollover=None, transmit_delay_1=None, transmit_delay_2=None, transmit_delay_3=None, transmit_delay_4=None, transmit_delay_5=None, receive_delay_1=None, receive_delay_2=None, receive_delay_3=None, receive_delay_4=None, receive_delay_5=None, data_quality=None, correction_angle_1=None, correction_angle_2=None, correction_doppler=None, correction_mag=None, correction_range=None, correction_rcs=None, correction_receive=None, correction_transmit=None, correction_aberration_yearly=None, correction_aberration_diurnal=None, corrections_applied=None), **data=None**)]), id='CCSDS_TDM_VERS', version='2.0')

In the input kvn file data section contains values. How can I solve it?

Regards.

Andrea Chessa

**Comment by egemenimre** [comment]
Hello,

Could you please post the tdm file as well, so that I can try it out? Due
to my current circumstances I may not be able to look at it promptly, but
rest assured that I will. :)

**Comment by chessasds** [comment]
In attachment the input file.
[tdm_opt_data.kvn.txt](https://github.com/egemenimre/ccsds-ndm/files/6636547/tdm_opt_data.kvn.txt)

**Comment by egemenimre** [comment]
Hi there, sorry for the long hiatus, unfortunately things have been rather chaotic on my end. I had a quick test with the current devel version and it looks fine to me. The following code reads the KVN file and converts it to XML. I can see the contents. Could you please test it?

 `def test_read_file():

    path = Path("data", "kvn", "tdm_opt_data.kvn")

    if path is not None:

        # read KVN file
        ndm = NdmIo().from_path(path)

        # print(ndm)
        print(NdmIo().to_string(ndm, NDMFileFormats.XML))
`
I will make a minor fix in a couple of days and issue an upgrade. If the above doesn't work, we can try with the updated version.
