### ISSUE TITLE
Released version does not contain source code

### ISSUE THREAD

**Issue by astrojuanlu** [egemenimre/ccsds-ndm#9]
Hi! :wave: (Coming from https://twitter.com/poliastro_py/status/1331735972883664898)

I tried `pip install ccsds_ndm` as explained in the README, but could not import any code. I realized that the wheel available from PyPI is almost empty:

```
$ unzip -l ccsds_ndm-1.0-py2.py3-none-any.whl 
Archive:  ccsds_ndm-1.0-py2.py3-none-any.whl
  Length      Date    Time    Name
---------  ---------- -----   ----
      210  2020-11-25 00:08   ccsds_ndm.py
    35149  2020-11-15 08:03   ccsds_ndm-1.0.dist-info/LICENSE
       99  2016-01-01 00:00   ccsds_ndm-1.0.dist-info/WHEEL
     5862  2016-01-01 00:00   ccsds_ndm-1.0.dist-info/METADATA
      363  2016-01-01 00:00   ccsds_ndm-1.0.dist-info/RECORD
---------                     -------
    41683                     5 files
$ cat ccsds_ndm.py 
# CCSDS-NDM: CCSDS Navigation Data Messages Read/Write Library
#
# Copyright (C) 2020 CCSDS-NDM Egemen Imre
#
# Licensed under GNU GPL v3.0. See LICENSE.rst for more info.
"""
CCSDS-NDM
"""
__version__ = "1.0"

```

So probably there is some sort of packaging problem.

**Comment by egemenimre** [comment]
Argh. Should be sorted now?

**Comment by astrojuanlu** [comment]
I see - that's because flit distinguishes between

- `module`: How you *import* the code. It must have a valid Python name (therefore, no hyphens allowed). Either (a) `my_module.py`, (b) `my_module/`, or (c) `src/my_module` (you had a mismatch before, now you switched to option b)
- `dist-name`: "If you want your package’s name on PyPI to be different from the importable module name, set this to the PyPI name." Hence, how you *install* the code.

I'm from my phone now, but I'll test the new release ASAP and let you know if it works. If you want to make changes, you're still in time I think!

**Comment by astrojuanlu** [comment]
This has already been fixed:

```python
>>> import ccsds_ndm
>>> ccsds_ndm.__version__
'1.1'
>>> from ccsds_ndm import ndm_io
>>> ndm_io.NdmIo
<class 'ccsds_ndm.ndm_io.NdmIo'>
```

closing!
